### ISSUE TITLE
replaceLogger

### ISSUE THREAD

**Issue by doque** [Gerhut/axios-debug-log#19]
Hi,

thanks for this great tool. I've got a small issue with it, however. By default, `debug` logs to `stderr`, which makes for rather nasty console.error messages:

![image](https://user-images.githubusercontent.com/1480751/35853246-4bd6683a-0b2d-11e8-8c4d-f62161f1e887.png)

I can use a custom logger that logs to `console.info` like this:

```js
const axiosLogger = require('debug')('axios');
axiosLogger.log = console.info.bind(console);
require('axios-debug-log').addLogger(apiClient, axiosLogger);
```

Unfortunately, this results in duplicate logging messages - the ones sent to stderr (the default logger) and my custom logger.

I'd love a way to only use my custom logger.

**Comment by Gerhut** [comment]
May add a logger as different namespace works? Which means

```javascript
const axiosLogger = require('debug')('axios-info');
axiosLogger.log = console.info.bind(console);
require('axios-debug-log').addLogger(apiClient, axiosLogger);
```

and run as

```sh
DEBUG=axios-info npm start
```

That will ignore the origin `axios` logger.

**Comment by doque** [comment]
Thank you!
