### ISSUE TITLE
Import instead of require

### ISSUE THREAD

**Issue by geoidesic** [Gerhut/axios-debug-log#44]
Hi,

How can I use `import` instead of `require`?
Or how can I use `require` within the context of imports?

My axios code is like so:
```
import axios from "axios";
const instance = axios.create(config);
let result = instance.axios.get('pings')
```

**Comment by Gerhut** [comment]
Are you asking about how to use axios instance? It seems your use of axios in the third line is not correct.

**Comment by Gerhut** [comment]
OK, I assume you asking about how to enable axios-debug-log in es module:

```js
import 'axios-debug-log';
```

Config:

```js
import config from 'axios-debug-log'
```
 in babel and

```ts
import config = require('axios-debug-log')
```

in typescript if no esModuleInterop is enabled

Customize

```js
import { addLogger } from 'axios-debug-log'
```

**Comment by geoidesic** [comment]
I couldn't get it to work, so I've gone to manual mocks. But thanks for the reply I might try again later.
