### ISSUE TITLE
No response from calls

### ISSUE THREAD

**Issue by jackhollowaypersonal** [Gerhut/axios-debug-log#53]
Hi, I installed your debug tool to try and figure out why an API call wasn't working within my project. I'm using 

const data = await axios({
stuff here
};

But not getting any response info, just the calls themselves? (URLs removed). Any help would be greatly appreciated
![Screenshot 2020-12-31 at 13 01 36](https://user-images.githubusercontent.com/62250647/103411619-d3618e00-4b68-11eb-8394-1a1a851a345a.png)

**Comment by Gerhut** [comment]
Seems your API calls are not responded, could you check that?

**Comment by jackhollowaypersonal** [comment]
> Seems your API calls are not responded, could you check that?

Hi, I don't know whether that's the case though, and thought your library could help ascertain that. Wireshark for mac proving unhelpful either

**Comment by Gerhut** [comment]
> > Seems your API calls are not responded, could you check that?
> 
> Hi, I don't know whether that's the case though, and thought your library could help ascertain that. Wireshark for mac proving unhelpful either

This is a server issue, if that is under your control and written in node.js, check if any `res.end()` is not forgotten in the request handler.
