### ISSUE TITLE
@types/debug as a devDependency

### ISSUE THREAD

**Issue by jmendiara** [Gerhut/axios-debug-log#55]
Currently, in package.json...
```json
  "dependencies": {
    "@types/debug": "^4.0.0",
    "debug": "^4.0.0"
  },
```

Is `@types/debug` a needed dependency, or could be moved to `devDependencies` ?

Having it in `dependencies` causes `@types/debug` to be installed in production builds, and the package is just typescript typings that are not needed in runtime

**Comment by Gerhut** [comment]
https://stackoverflow.com/questions/45176661/how-do-i-decide-whether-types-goes-into-dependencies-or-devdependencies

**Comment by jmendiara** [comment]
I _guess_ you are saying that having in `dependencies` is intended. Closing
